# Pandas Revision

Syntax on `placement.csv`, practice on `food_orders.csv`.

In [5]:
import pandas as pd

df = pd.read_csv('/Users/snehayadav/Desktop/Assign.Python/placement.csv')      # syntax examples
food = pd.read_csv('/Users/snehayadav/Desktop/Assign.Python/food_orders.csv')  # practice

---
## 1. First look

In [55]:
# size: (rows, columns)
df.shape
food.head(4)

,order_id,city,cuisine,day,order_hour,quantity,distance_km,order_value,delivery_time_min,payment,rating,tip,was_late
0,ORD10591,Mumbai,Chinese,Thu,22,3,4.5,519,27,Card,NaN,15.0,No
1,ORD10520,Pune,Chinese,Sat,14,1,14.0,295,60,Cash,3.0,15.0,Yes
2,ORD10588,Hyderabad,Chinese,Sat,22,3,11.8,744,44,UPI,3.0,NaN,Yes
3,ORD10113,Delhi,Desserts,Mon,22,3,5.2,370,36,UPI,5.0,20.0,No

In [6]:
# numeric summary: count, mean, min, max
df.describe().round(2)

,cgpa,twelfth_percent,internships,projects,backlogs,prep_hours,communication_score,package_lpa
count,550.00,550.00,519.00,550.00,550.00,454.00,538.00,517.00
mean,7.36,77.60,1.30,2.56,0.68,153.15,6.27,4.71
std,0.98,10.12,1.18,1.49,1.10,86.06,1.69,3.48
min,5.00,55.00,0.00,0.00,0.00,16.00,1.10,0.00
25%,6.69,70.90,0.00,1.00,0.00,90.00,5.20,0.00
50%,7.40,77.90,1.00,2.00,0.00,134.00,6.30,6.01
75%,7.98,84.50,2.00,4.00,1.00,192.75,7.40,7.28
max,10.00,98.00,4.00,6.00,4.00,500.00,10.00,12.56

In [57]:
# column types and non-null counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   student_id           550 non-null    str
 1   cgpa                 550 non-null    float64
 2   twelfth_percent      550 non-null    float64
 3   branch               550 non-null    str
 4   internships          519 non-null    float64
 5   projects             550 non-null    int64
 6   backlogs             550 non-null    int64
 7   prep_hours           454 non-null    float64
 8   communication_score  538 non-null    float64
 9   hostel               550 non-null    str
 10  placed               550 non-null    str
 11  package_lpa          517 non-null    float64
dtypes: float64(6), int64(2), str(4)
memory usage: 51.7 KB

### Practice

**Q1.** How many orders are in the file, and how many details are stored for each order?

In [58]:
print(food.shape)

(612, 13)

**Q2.** Someone ordered food worth a small EMI. Find the biggest order value and the longest delivery time using one command.

In [59]:
food[['order_value', 'delivery_time_min']].max()

order_value          2354
delivery_time_min      63
dtype: int64

**Q3.** Which columns hold numbers and which hold text?

In [60]:
print(food.dtypes)

order_id                 str
city                     str
cuisine                  str
day                      str
order_hour             int64
quantity               int64
distance_km          float64
order_value            int64
delivery_time_min      int64
payment                  str
rating               float64
tip                  float64
was_late                 str
dtype: object

---
## 2. Selecting

In [7]:
# one column
df['cgpa']

0      7.41
1      7.52
2      7.35
3      7.86
4      5.63
       ...
545    8.40
546    7.60
547    6.33
548    8.86
549    8.45
Name: cgpa, Length: 550, dtype: float64

In [62]:
# many columns: a list inside [ ]
df[['branch', 'cgpa', 'placed']].head()

  branch  cgpa placed
0     IT  7.41     No
1    CSE  7.52    Yes
2    CSE  7.35    Yes
3    CSE  7.86    Yes
4    CSE  5.63    Yes

In [63]:
# iloc: by position -> rows, columns
df.iloc[0:5, 0:3]

  student_id  cgpa  twelfth_percent
0     VS2821  7.41             78.5
1     VS3068  7.52             70.0
2     VS2940  7.35             78.3
3     VS3138  7.86             60.2
4     VS2670  5.63             88.3

In [64]:
# loc: by label -> rows, column names (both ends included)
df.loc[0:4, 'cgpa':'internships']

   cgpa  twelfth_percent branch  internships
0  7.41             78.5     IT          0.0
1  7.52             70.0    CSE          2.0
2  7.35             78.3    CSE          2.0
3  7.86             60.2    CSE          1.0
4  5.63             88.3    CSE          2.0

### Practice

**Q4.** The manager's eyes hurt after 13 columns. Show only `city`, `cuisine` and `order_value` for the first 10 orders.

In [65]:
food[["city","cuisine","order_value"]].head(10)#if all of this are in sequence wise then can use loc.

        city       cuisine  order_value
0     Mumbai       Chinese          519
1       Pune       Chinese          295
2  Hyderabad       Chinese          744
3      Delhi      Desserts          370
4      Delhi        Burger          594
5     Mumbai       Biryani          933
6  Hyderabad  South Indian          197
7       Pune       Biryani         1482
8  Bangalore       Biryani          522
9       Pune  South Indian          233

**Q5.** The printer jammed and printed only rows 50 to 54, first 5 columns. Recreate that page using positions.

In [66]:
food.iloc[50:55,0:5]

    order_id       city       cuisine  day  order_hour
50  ORD10161  Bangalore         Pizza  Sun          22
51  ORD10156       Pune      Desserts  Mon          21
52  ORD10160      Delhi      Desserts  Sat          20
53  ORD10310       Pune      Desserts  Sun          13
54  ORD10018     Mumbai  South Indian  Sat          18

**Q6.** Using labels, show rows 100 to 105 and every column from `city` to `order_hour`.

In [67]:
food.loc[100:105,'city':'order_hour']

          city       cuisine  day  order_hour
100       Pune       Biryani  Sat          12
101       Pune        Burger  Sun          21
102     Mumbai         Pizza  Thu          17
103  Bangalore       Biryani  Sun          19
104     Mumbai         Pizza  Sun          23
105     Mumbai  South Indian  Sun          13

---
## 3. Filtering and sorting

In [8]:
# one condition
df[df['cgpa'] > 8]

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
14,VS2701,9.01,64.8,ECE,1.0,0,1,NaN,4.8,Yes,Yes,6.70
16,VS3012,8.29,77.8,CSE,0.0,2,0,81.0,7.9,Yes,Yes,8.06
17,VS2892,8.84,86.3,Civil,1.0,2,0,132.0,3.4,No,Yes,5.77
18,VS2936,8.23,69.5,CSE,3.0,3,1,119.0,6.9,Yes,Yes,8.54
21,VS2930,8.07,83.1,Mech,1.0,2,0,120.0,9.5,Yes,Yes,5.38
...,...,...,...,...,...,...,...,...,...,...,...,...
537,VS2668,8.21,74.2,CSE,0.0,4,0,157.0,5.5,Yes,Yes,7.66
539,VS2966,8.45,80.9,Mech,2.0,2,1,90.0,7.6,No,Yes,7.31
545,VS2811,8.40,79.7,ECE,1.0,4,0,173.0,5.0,Yes,Yes,6.22
548,VS2796,8.86,78.2,ECE,3.0,1,0,259.0,6.4,Yes,Yes,7.51
549,VS2775,8.45,70.7,CSE,0.0,3,0,NaN,5.1,Yes,Yes,8.45

In [69]:
# two conditions: & is and, | is or, each in its own ( )
df[(df['cgpa'] > 8) & (df['backlogs'] == 0)]

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
16,VS3012,8.29,77.8,CSE,0.0,2,0,81.0,7.9,Yes,Yes,8.06
17,VS2892,8.84,86.3,Civil,1.0,2,0,132.0,3.4,No,Yes,5.77
21,VS2930,8.07,83.1,Mech,1.0,2,0,120.0,9.5,Yes,Yes,5.38
44,VS3139,8.85,81.2,Mech,0.0,3,0,194.0,7.4,No,Yes,6.89
47,VS2788,8.09,84.6,Mech,0.0,2,0,220.0,6.0,Yes,No,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
534,VS3112,8.37,63.9,CSE,4.0,2,0,103.0,5.9,Yes,Yes,7.52
537,VS2668,8.21,74.2,CSE,0.0,4,0,157.0,5.5,Yes,Yes,7.66
545,VS2811,8.40,79.7,ECE,1.0,4,0,173.0,5.0,Yes,Yes,6.22
548,VS2796,8.86,78.2,ECE,3.0,1,0,259.0,6.4,Yes,Yes,7.51
549,VS2775,8.45,70.7,CSE,0.0,3,0,NaN,5.1,Yes,Yes,8.45

In [9]:
# value is one of many
df[df['branch'].isin(['CSE', 'IT'])]

# value inside a range (both ends included)
df[df['cgpa'].between(7, 8)]

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
0,VS2821,7.41,78.5,IT,0.0,6,1,188.0,4.3,No,No,0.00
1,VS3068,7.52,70.0,CSE,2.0,3,0,167.0,9.8,Yes,Yes,10.06
2,VS2940,7.35,78.3,CSE,2.0,0,3,199.0,4.8,Yes,Yes,NaN
3,VS3138,7.86,60.2,CSE,1.0,3,0,135.0,8.0,No,Yes,8.63
6,VS2971,7.79,74.7,CSE,0.0,4,0,NaN,7.3,Yes,No,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
536,VS3032,7.53,83.5,ECE,0.0,2,3,20.0,6.7,No,No,0.00
542,VS2998,7.81,63.4,IT,4.0,4,0,89.0,5.1,Yes,Yes,8.52
543,VS2785,7.19,77.5,ECE,3.0,4,0,84.0,6.5,No,Yes,6.68
544,VS2948,7.18,87.2,ECE,NaN,1,1,296.0,4.2,Yes,No,0.00
546,VS3102,7.60,76.5,Civil,0.0,4,0,NaN,6.7,Yes,Yes,5.68

In [10]:
# count of each category
df['branch'].value_counts()

branch
CSE      167
IT       118
ECE      112
Mech     103
Civil     50
Name: count, dtype: int64

In [72]:
# sort, biggest first
df.sort_values('cgpa', ascending=False).head()

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
113,VS3148,10.00,93.9,Mech,3.0,3,0,190.0,6.8,Yes,Yes,9.17
500,VS2917,10.00,84.0,ECE,0.0,4,0,58.0,6.3,No,Yes,8.54
265,VS2702,9.95,86.5,CSE,2.0,0,0,248.0,7.0,No,Yes,10.03
185,VS3124,9.85,63.8,CSE,0.0,4,0,87.0,7.5,Yes,Yes,8.77
157,VS2747,9.78,85.3,ECE,2.0,2,0,NaN,5.3,Yes,Yes,NaN

### Practice

**Q7.** Biryani at 2 AM is not hunger, it is a lifestyle. Count the Biryani orders placed between midnight and 3 AM (hours 0 to 3).

In [11]:
food[(food['cuisine'] == 'Biryani') & (food['order_hour'].between(0, 3))].shape[0] # this shape is for rows.

35

**Q8.** Someone in Pune is clearly throwing a party. Show Pune orders worth more than 1000 rupees. How many?

In [12]:
food[(food['city'] == 'Pune') & (food['order_value'] > 1000)].shape[0]

23

**Q9.** A food blogger survives only on Pizza and Burger. How many such orders are there?

In [13]:
food[(food['cuisine'].isin(['Pizza','Burger']))]

,order_id,city,cuisine,day,order_hour,quantity,distance_km,order_value,delivery_time_min,payment,rating,tip,was_late
4,ORD10322,Delhi,Burger,Fri,14,4,7.2,594,29,UPI,5.0,10.0,No
13,ORD10033,Delhi,Pizza,Sun,14,2,0.6,602,21,UPI,5.0,20.0,No
17,ORD10531,Delhi,Burger,Sun,13,6,4.9,1115,37,UPI,NaN,25.0,No
18,ORD10098,Hyderabad,Pizza,Fri,21,2,3.2,511,24,Card,NaN,NaN,No
22,ORD10091,Hyderabad,Burger,Mon,18,4,8.3,640,37,UPI,5.0,20.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
589,ORD10396,Delhi,Burger,Sat,21,3,11.1,681,42,Cash,3.0,15.0,Yes
590,ORD10130,Bangalore,Pizza,Fri,17,2,4.3,419,36,UPI,4.0,35.0,No
598,ORD10239,Mumbai,Burger,Sat,21,1,3.1,268,33,Cash,4.0,25.0,No
608,ORD10057,Bangalore,Pizza,Sun,21,2,3.7,594,29,Card,5.0,NaN,No
611,ORD10383,Bangalore,Pizza,Fri,19,2,2.7,437,31,Cash,3.0,40.0,No

**Q10.** How many deliveries fell in the *"bhaiya, kahan ho?"* zone of 30 to 45 minutes?

In [14]:
food[food['delivery_time_min'].between(30, 45)].shape[0]

222

**Q11.** Does anyone still pay in cash? Count the orders by payment method.

In [15]:
food['payment'].value_counts()

payment
UPI     363
Card    154
Cash     95
Name: count, dtype: int64

**Q12.** Someone definitely ordered for the whole hostel. Show the 5 biggest orders with `city`, `cuisine`, `quantity` and `order_value`.

In [83]:
food.sort_values("order_value", ascending=False )[['city', 'cuisine','quantity','order_value']].head(5)

          city  cuisine  quantity  order_value
586  Hyderabad  Biryani         8         2354
544  Hyderabad  Biryani         8         2254
476     Mumbai  Biryani         8         2114
367       Pune  Biryani         8         1944
388  Hyderabad  Biryani         6         1895

**Q13.** Which delivery partners were basically The Flash? Show the 5 fastest deliveries with `city`, `distance_km` and `delivery_time_min`.

In [ ]:
food.sort_values("delivery_time_min")[['city', 'distance_km','delivery_time_min']].head(5)#. by default head is 5.

          city  distance_km  delivery_time_min
325       Pune          1.2                  8
580       Pune          1.4                  8
480      Delhi          1.0                  8
121  Hyderabad          1.3                  8
458      Delhi          1.4                  9

---
## 4. Cleaning

In [16]:
# blanks per column
df.isnull().sum()

student_id              0
cgpa                    0
twelfth_percent         0
branch                  0
internships            31
projects                0
backlogs                0
prep_hours             96
communication_score    12
hostel                  0
placed                  0
package_lpa            33
dtype: int64

In [17]:
# repeated rows
print(df.duplicated().sum())

# remove repeated rows
df_clean = df.drop_duplicates()

0

In [18]:
# remove rows where one column is blank
df_clean = df_clean.dropna(subset=['internships'])

# fill blanks with a value
df_clean['prep_hours'] = df_clean['prep_hours'].fillna(0)

# change the type
df_clean['internships'] = df_clean['internships'].astype(int)

In [19]:
# new column from existing columns
df_clean['cgpa_percent'] = (df_clean['cgpa'] * 9.5).round(1)
df_clean[['cgpa', 'cgpa_percent']].head()

   cgpa  cgpa_percent
0  7.41          70.4
1  7.52          71.4
2  7.35          69.8
3  7.86          74.7
4  5.63          53.5

### Practice

**Q14.** Count the blanks in every column.

In [20]:
food.isnull().sum()

order_id               0
city                   0
cuisine                0
day                    0
order_hour             0
quantity               0
distance_km            8
order_value            0
delivery_time_min      0
payment                0
rating               107
tip                  185
was_late               0
dtype: int64

**Q15.** The app got confused and saved some orders twice. How many repeated rows are there?

In [21]:
print(food.duplicated().sum())

12

**Q16.** Remove the repeated orders before customers get charged twice. Print the shape.

In [22]:
food_clean = food.drop_duplicates()
print(food.shape)

(612, 13)

**Q17.** GPS failed for some orders, so the delivery partner took the scenic route. Remove the rows with a blank `distance_km` and print the shape.

In [23]:
food = food.dropna(subset=['distance_km'])
print(food.shape)

(604, 13)

**Q18.** A blank tip means no tip, and one sad delivery partner. Fill the blanks in `tip` with 0 and make it a whole number.

In [24]:
food['tip'] = food['tip'].fillna(0).astype(int)

**Q19.** Add a column `value_per_item`: order value divided by quantity, rounded.

In [25]:
food['value_per_item'] = (food['order_value'] / food['quantity']).round()

---
## 5. Grouping and saving

In [26]:
# average per group
df.groupby('branch')['cgpa'].mean()

branch
CSE      7.484431
Civil    7.341200
ECE      7.377054
IT       7.183051
Mech     7.342233
Name: cgpa, dtype: float64

In [27]:
# sorted, highest first
df.groupby('branch')['cgpa'].mean().sort_values(ascending=False)

branch
CSE      7.484431
ECE      7.377054
Mech     7.342233
Civil    7.341200
IT       7.183051
Name: cgpa, dtype: float64

In [28]:
# other numbers per group
df.groupby('branch')['cgpa'].max()
df.groupby('branch')['internships'].sum()
df.groupby('branch')['student_id'].count()

branch
CSE      167
Civil     50
ECE      112
IT       118
Mech     103
Name: student_id, dtype: int64

In [29]:
# save to a file, without the index column
df_clean.to_csv('placement_clean.csv', index=False)

### Practice

**Q20.** Which city is the stingiest tipper? Find the average tip per city, lowest first.

In [30]:
food.groupby('city')['tip'].mean().sort_values()

city
Delhi        12.650000
Hyderabad    16.274510
Pune         20.489510
Mumbai       23.095238
Bangalore    29.248120
Name: tip, dtype: float64

**Q21.** Is the weekend really a party? Find the average order value for each day, highest first.

In [31]:
food.groupby('day')['order_value'].mean().sort_values(ascending=False)

day
Sat    670.210884
Sun    661.632000
Fri    584.129032
Tue    562.818182
Wed    556.645161
Mon    554.787879
Thu    544.059701
Name: order_value, dtype: float64

**Q22.** Does a late delivery earn an angry rating? Compare the average rating of late and on-time orders.

In [ ]:
food.groupby('delivery_time_min')['rating'].mean()

delivery_time_min
8     3.500000
9     4.500000
10    5.000000
11    3.666667
12    3.833333
13    4.333333
14    4.333333
15    4.166667
16    4.307692
17    3.937500
18    4.294118
19    4.250000
20    4.100000
21    4.277778
22    3.875000
23    4.000000
24    4.166667
25    4.333333
26    4.384615
27    4.000000
28    4.400000
29    4.096774
30    4.222222
31    4.275862
32    4.250000
33    4.190476
34    4.375000
35    4.000000
36    4.187500
37    4.272727
38    4.300000
39    4.250000
40    4.166667
41    3.750000
42    2.600000
43    4.000000
44    3.000000
45    3.600000
46    2.200000
47    2.750000
48    3.666667
49    3.000000
51    3.400000
52    3.000000
53    3.000000
56         NaN
57    3.000000
59    4.000000
60    3.000000
62    3.000000
63    2.000000
Name: rating, dtype: float64

**Q23.** Which city holds the record for the single biggest order after cleaning? Find the highest order value in each city.

In [34]:
food.groupby('city')['order_value'].max().sort_values(ascending=False)

city
Hyderabad    2254
Mumbai       2114
Pune         1944
Bangalore    1687
Delhi        1618
Name: order_value, dtype: int64

**Q24.** Which payment method brings in the most money? Find the total order value for each payment method.

In [36]:
food.groupby('payment')['order_value'].sum().sort_values(ascending=False)

payment
UPI     215834
Card     95488
Cash     56571
Name: order_value, dtype: int64

**Q25.** Which cuisine is the nation's favourite? Count the orders for each cuisine.

In [37]:
food['cuisine'].value_counts()

cuisine
Biryani         138
Pizza           114
South Indian    107
Chinese         104
Burger           74
Desserts         67
Name: count, dtype: int64

**Q26.** Save the cleaned data as `food_orders_clean.csv` without the index column.

In [38]:
food.to_csv('food_orders_clean.csv', index=False)

---
*Q16 to Q19 change `food`. Run them only once, in order.*